### ISSUE TITLE
单栏模式下设置图标会被挤没

### ISSUE THREAD

**Issue by clay-y** [zhihuifanqiechaodan/vue3-element-admin#3]
<img width="1436" alt="截屏2023-05-05 17 55 29" src="https://user-images.githubusercontent.com/93634662/236428366-ff634d0a-5d33-4e86-987a-e3ace478c7eb.png">

**Comment by zhihuifanqiechaodan** [comment]
> <img width="1436" alt="截屏2023-05-05 17 55 29" src="https://user-images.githubusercontent.com/93634662/236428366-ff634d0a-5d33-4e86-987a-e3ace478c7eb.png">
> 
> 

ok，这段时间我改下样式。
