### ISSUE TITLE
没有文档啊

### ISSUE THREAD

**Issue by liuyue-niann** [zhihuifanqiechaodan/vue3-element-admin#4]
文档在哪啊

**Comment by zhihuifanqiechaodan** [comment]
> 文档在哪啊

啊，木有文档呀，直接看代码。不懂的直接问

**Comment by CallMeDarren** [comment]
他这个是基于花裤衩大佬的项目魔改的，可以参考下https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/deploy.html#%E6%9E%84%E5%BB%BA

**Comment by zhihuifanqiechaodan** [comment]
> 他这个是基于花裤衩大佬的项目魔改的，可以参考下https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/deploy.html#%E6%9E%84%E5%BB%BA

没错👍

**Comment by liuyue-niann** [comment]
之前那个路由丢失的问题，最近部署上去就没有这个问题
















在 2023-07-25 22:53:16，"高宇" ***@***.***> 写道：

他这个是基于花裤衩大佬的项目魔改的，可以参考下https://panjiachen.gitee.io/vue-element-admin-site/zh/guide/essentials/deploy.html#%E6%9E%84%E5%BB%BA

没错

**Comment by zhihuifanqiechaodan** [comment]
> 

嗯嗯，最近在做一个新的调整，关于路由权限以及按钮权限的设计，后续更新了可以参考一下。
