### ISSUE TITLE
出现警告就路由丢失

### ISSUE THREAD

**Issue by liuyue-niann** [zhihuifanqiechaodan/vue3-element-admin#5]
https://gitee.com/LiuYue_24-XiaoHui/online-education-system.git

**Comment by zhihuifanqiechaodan** [comment]
> https://gitee.com/LiuYue_24-XiaoHui/online-education-system.git

gitee的仓库我没有维护，github的也有这个问题吗，可以贴出来报错信息看看

**Comment by liuyue-niann** [comment]
解决了、应该是vue原本的bug



















在 2023-07-08 17:09:09，"高宇" ***@***.***> 写道：

https://gitee.com/LiuYue_24-XiaoHui/online-education-system.git

gitee的仓库我没有维护，github的也有这个问题吗，可以贴出来报错信息看看

**Comment by zhihuifanqiechaodan** [comment]
> 解决了、应该是vue原本的bug
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 在 2023-07-08 17:09:09，"高宇" ***@***.***> 写道：
> 
> https://gitee.com/LiuYue_24-XiaoHui/online-education-system.git
> 
> gitee的仓库我没有维护，github的也有这个问题吗，可以贴出来报错信息看看
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

好的，欢迎提出更多问题和修改建议
