### ISSUE TITLE
在dashboard和其他页签切换的时候，keep-alive失效了

### ISSUE THREAD

**Issue by peiwuqing** [zhihuifanqiechaodan/vue3-element-admin#6]
打开一个keep-alive缓存的页面A，在打开一个keep-alive缓存的页面B，这两个页面都设置了noCache:false，A,B两个页面互相切换时没有问题，但是一切换到dashboard 时  A个B两个页面的缓存同时就失效了，所以你那个进来的主路由 / 应该只负责跳转，跳转到dashboard页面的新路由就可以了

**Comment by zhihuifanqiechaodan** [comment]
> 打开一个keep-alive缓存的页面A，在打开一个keep-alive缓存的页面B，这两个页面都设置了noCache:false，A,B两个页面互相切换时没有问题，但是一切换到dashboard 时  A个B两个页面的缓存同时就失效了，所以你那个进来的主路由 / 应该只负责跳转，跳转到dashboard页面的新路由就可以了有在你的页面上设置name嘛，缓存不止需要在路由表设置，页面上也需要写
